import { Resend } from "resend";
import logger from "../config/logger.js";

/**
 * Send the generated sales summary to the user via Resend API.
 */
export async function sendEmail(
  to: string,
  summary: string
): Promise<void> {
  const apiKey = process.env.RESEND_API_KEY;

  if (!apiKey) {
    logger.warn(
      "RESEND_API_KEY is not configured. Skipping email delivery. Set it in your .env file."
    );
    return;
  }

  const resend = new Resend(apiKey);

  const htmlBody = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 700px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f8f9fa;
    }
    .container {
      background: #ffffff;
      border-radius: 8px;
      padding: 32px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.08);
    }
    h1, h2, h3 { color: #1a1a2e; }
    h1 { border-bottom: 2px solid #e94560; padding-bottom: 12px; }
    ul { padding-left: 20px; }
    li { margin-bottom: 6px; }
    .footer {
      margin-top: 32px;
      padding-top: 16px;
      border-top: 1px solid #eee;
      font-size: 12px;
      color: #888;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>📊 Sales Insight Summary</h1>
    <pre style="white-space: pre-wrap; font-family: inherit;">${summary}</pre>
    <div class="footer">
      Generated by Sales Insight Automator • ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
    </div>
  </div>
</body>
</html>`;

  logger.info(`Sending email to ${to} via Resend...`);

  try {
    const { data, error } = await resend.emails.send({
      from: "onboarding@resend.dev",
      to: [to],
      subject: "Sales Insight Summary",
      text: summary,
      html: htmlBody,
    });

    if (error) {
      logger.error("Error from Resend API:", { error });
      return;
    }

    logger.info("Email sent successfully via Resend", { id: data?.id });
  } catch (error) {
    logger.error("Failed to send email via Resend", { error });
  }
}
